spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: sua_senha_aqui
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
